Resources:
  PageViewsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: '#{AWS::AccountId}'
      DatabaseName: '#{AccessLogsDatabase}'
      TableInput:
        Name: '${self:custom.glue.tables.pageViews}'
        Description: 'Page views table'
        TableType: EXTERNAL_TABLE
        Parameters: { 'has_encrypted_data': 'false', 'parquet.compression': 'SNAPPY' }
        PartitionKeys:
          - Name: event_date
            Type: string
          - Name: event_hour
            Type: string
          - Name: domain_name
            Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Columns:
            - Name: event_year
              Type: string
            - Name: event_month
              Type: string
            - Name: event_day
              Type: string
            - Name: event_timestamp
              Type: timestamp
            - Name: edge_location
              Type: string
            - Name: edge_city
              Type: string
            - Name: edge_state
              Type: string
            - Name: edge_country
              Type: string
            - Name: edge_latitude
              Type: float
            - Name: edge_longitude
              Type: float
            - Name: url
              Type: string
            - Name: path
              Type: string
            - Name: referrer
              Type: string
            - Name: user_agent
              Type: string
            - Name: timezone
              Type: string
            - Name: device_outer_resolution
              Type: string
            - Name: device_inner_resolution
              Type: string
            - Name: device_color_depth
              Type: int
            - Name: device_platform
              Type: string
            - Name: device_memory
              Type: int
            - Name: device_cores
              Type: int
            - Name: browser_language
              Type: string
            - Name: source
              Type: string
            - Name: utm_source
              Type: string
            - Name: utm_campaign
              Type: string
            - Name: utm_medium
              Type: string
            - Name: utm_content
              Type: string
            - Name: utm_term
              Type: string
            - Name: cloudfront_cache_type
              Type: string
            - Name: cloudfront_time_taken_ms
              Type: int
            - Name: cloudfront_http_version
              Type: string
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: 's3://#{LogBucket}/${self:custom.prefixes.pageViews}'
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
