Resources:
  PartitionedParquetTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: '#{AWS::AccountId}'
      DatabaseName: '#{AccessLogsDatabase}'
      TableInput:
        Name: '${self:custom.glue.tables.optimized}'
        Description: 'Parquet format access logs as transformed from gzip version'
        TableType: EXTERNAL_TABLE
        Parameters: { 'has_encrypted_data': 'false', 'parquet.compression': 'SNAPPY' }
        PartitionKeys:
        - Name: year
          Type: string
        - Name: month
          Type: string
        - Name: day
          Type: string
        - Name: hour
          Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Columns:
          - Name: date
            Type: date
          - Name: time
            Type: string
          - Name: edge_location
            Type: string
          - Name: edge_location_prefix
            Type: string
          - Name: bytes
            Type: bigint
          - Name: request_ip
            Type: string
          - Name: status
            Type: int
          - Name: referrer
            Type: string
          - Name: user_agent
            Type: string
          - Name: result_type
            Type: string
          - Name: response_result_type
            Type: string
          - Name: request_bytes
            Type: bigint
          - Name: time_taken
            Type: float
          - Name: x_forwarded_for
            Type: string
          - Name: http_version
            Type: string
          - Name: timezone
            Type: string
          - Name: device_outer_resolution
            Type: string
          - Name: device_inner_resolution
            Type: string
          - Name: device_color_depth
            Type: int
          - Name: device_platform
            Type: string
          - Name: device_memory
            Type: int
          - Name: device_cores
            Type: int
          - Name: browser_language
            Type: string
          - Name: source
            Type: string
          - Name: utm_source
            Type: string
          - Name: utm_campaign
            Type: string
          - Name: utm_medium
            Type: string
          - Name: utm_content
            Type: string
          - Name: utm_term
            Type: string
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: 's3://#{LogBucket}/${self:custom.prefixes.partitionedParquet}'
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
